### ISSUE TITLE
List API call crash when replicas are not set

### ISSUE THREAD

**Issue by stefanprodan** [openfaas-incubator/openfaas-operator#20]
When the replicas field has no value the `/list` API call fails.

**Comment by alexellis** [comment]
When is the replica field empty?

**Comment by stefanprodan** [comment]
When you want HPA v2. Here is an example: https://github.com/stefanprodan/openfaas-flux#manage-openfaas-functions-and-auto-scaling-with-weave-flux

**Comment by stefanprodan** [comment]
If you define a function with `replicas` the HPA will fight with the Operator control loop:

```yaml
apiVersion: o6s.io/v1alpha1
kind: Function
metadata:
  name: sentimentanalysis
  namespace: openfaas-fn
spec:
  replicas: 1
  name: sentimentanalysis
  image: functions/sentimentanalysis
```

In order to let HPA take over you should omit the `replicas` field and set the resources spec:

```yaml
apiVersion: o6s.io/v1alpha1
kind: Function
metadata:
  name: sentimentanalysis
  namespace: openfaas-fn
spec:
  name: sentimentanalysis
  image: functions/sentimentanalysis
  limits:
    cpu: "2000m"
    memory: "512Mi"
  requests:
    cpu: "10m"
    memory: "64Mi"
```
