### ISSUE TITLE
The operator is consuming massive resources and crashing the Kubernetes API server

### ISSUE THREAD

**Issue by def1oyd** [openfaas-incubator/openfaas-operator#50]
I have upgraded my openfaas-operator to 0.8.8 in order to fix #47  (Thanks for the quick fix!)
Unfortunately I am facing the similar problem.

## Expected Behaviour

Function deployments and services are updated without any error.

## Current Behaviour

After upgraded, the pods / deployments were getting killed and recreated again and again like in #47.

Then I dig into the log of the operator, and got the following

```bash
I0921 19:53:29.325471       1 deployment.go:241] Function my-func annotations have changed
I0921 19:53:29.325505       1 controller.go:316] Updating deployment for 'my-func'
E0921 19:53:30.406757       1 controller.go:328] Updating deployment for 'my-func' failed: Deployment.apps "my-func" is invalid: [metadata.annotations: Too long: must have at most 262144 characters, spec.template.annotations: Too long: must have at most 262144 characters]
E0921 19:53:32.305706       1 controller.go:339] Updating service for 'my-func' failed: Service "my-func" is invalid: metadata.annotations: Too long: must have at most 262144 characters
...
```

Similar to #47, the operator was looping these lines all the time, with a short interval.

After a while (like ~5 minutes), my monitor reported that 2 of my master nodes had crashed.

I checked the kubernetes-dashboard, it was reporting the deployment `gateway`, which has gateway and operator inside, was using ~8GB memory, I forgot the CPU usage, but it was not low.

Later I reverted the upgrade and things went back to normal.

## Possible Solution

I guess the operator was in a dead loop attempting to update the deployment and the service, but it couldn't make it because of the `*.metadata.annotations: Too long` problem.

## Steps to Reproduce (for bugs)

1. On an older version of `openfass-operator`, `0.8.6`, patched with the code snippet mentioned in #47
2. Deploy the following function

    registry-secret.yml
    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
    name: registry-secret
    namespace: faas
    type: kubernetes.io/dockercfg
    data:
    .dockercfg: xxxxxxx
    ```

    my-func-secret.yml
    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
    name: my-func-secret
    namespace: faas
    type: Opaque
    data:
    DB_HOST: xxx
    DB_NAME: xxx
    DB_PORT: xxx
    DB_USER: xxx
    DB_PASS: xxx
    ```

    stack.yml
    ```yaml
    provider:
    name: faas
    gateway: http://gateway

    functions:
    my-func:
        lang: go
        handler: ./function
        image: private.registry/my-func:0.0.1 
        environment:
        ENV_1: "1"
        combine_output: false
        secrets:
        - registry-secret
        - my-func-secret
    ```

    Please note that these are mocks, I am not allowed to share the real ones, sorry about that.
    Some stats for my real YAMLs
    * Length of the function name - `26 characters`
    * Length of the image name - `125 characters`
    * Length of the namespace - `8 characters`

3. Confirm the function is deployed successfully and working without error, test with OpenFaaS Portal
4. Edit the deployment with `kubectl edit`, change the image tag of the `openfaas-operator` to `0.8.8`
5. Disaster happens

## Context

I am trying to deploy a function which its image is in a private registry.

I provided the secret for the private registry via the fuction YAML.

It didn't work because the secrets part of the deployment comparison was not working probably, the deployments were always recognized changed, and the operator was always trying to update the deployment.

Then I raised #47, and 0.8.8 has been released to fix the problem.

However I still cannot make it working because of the `*.metadata.annotations: Too long` problem.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
17.09.0-ce
```

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```bash
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):
```
Ubuntu 16.04.4 LTS
```
